### ISSUE TITLE
Error during `azd up`

### ISSUE THREAD

**Issue by skprasadu** [bwilliams2/azure-search-openai-demo#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> As mentioned in the documentation, I created a custom role, with permissions for Microsoft.Resources/deployments* at the Subscription level and added myself to it. And did `azd login`, `azd init -t bwilliams2/azure-search-openai-demo` and finally did `azd up`, and it is erroring out in the 1st step itself.

### Any log messages given by the failure
> I am getting below error, 

ERROR: deployment failed: error deploying infrastructure: failed deploying: starting deployment to subscription: PUT https://management.azure.com/subscriptions/08222f67-7711-41f7-a9cf-21fec2518171/providers/Microsoft.Resources/deployments/tce-openai-search
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: SubscriptionNotFound
--------------------------------------------------------------------------------
{
  "error": {
    "code": "SubscriptionNotFound",
    "message": "The subscription '/subscriptions/08222f67-7711-41f7-a9cf-21fec2518171' could not be found."
  }
}

### Expected/desired behavior
>

I would have expected it to bring this up. Similar to the original branch.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bwilliams2** [comment]
@skprasadu I made some updates to the subscription references during the deployment within PR #7. Check if this fixes your subscription error above.
